### PR TITLE
KARMA added

### PR DESCRIPTION
**Pull request by towardthesea**
This pull request includes:
- Adding `subSystem_KARMA` class
- Modification in `icubClient` with some actions (**push**, **draw**, **vdraw**) from the new `subSystem_KARMA`
- Adding a new example in simulation to check the behavior of `icubClient` with `KARMA`
- Modifications of some related files to include new `subSystem_KARMA`

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Hi @towardthesea,
This is looking pretty good! On a first glance, I saw that you use tabs instead of spaces in some files. Can you please change the tabs to be 4 spaces to be consistent with the rest of the project?
I'll have a more detailed look tomorrow.

Thanks!
Tobi

**Comment by Tobias-Fischer** [comment]
Just the tabs in the `ini` files left now :).
@pattacini: Do you think it's smart calling the Karma-push `push` as well, or should we use another verb seeing that there might be confusions with the `ARE` push?

**Comment by pattacini** [comment]
@Tobias-Fischer I reckon you're definitely right.

@towardthesea it'd be better to modify the name of those methods in the `iCubClient`, not to mess with others. Any suggestion?

**Comment by towardthesea** [comment]
Fix tabs in  `ini` files @Tobias-Fischer. Previously I used `gedit` to edit then couldn't recognize the different :(

**Comment by towardthesea** [comment]
How about `push-Karma` or `pushKarma`.
If we do so, I think we should also change `draw` and `vdraw` too!

**Comment by pattacini** [comment]
@towardthesea :+1:, also for updating the remaining methods' names.

**Comment by Tobias-Fischer** [comment]
Sounds good guys :+1:

**Comment by towardthesea** [comment]
Modified, tested and pushed!

**Comment by Tobias-Fischer** [comment]
Hi @towardthesea,
Sorry to be picky, but there are still some tabs left in `client_KARMA.ini` and `example_KARMA.ini`. As soon as they are changed to spaces, I'm happy to merge :+1: 
Best, Tobi

**Comment by Tobias-Fischer** [comment]
Working nicely. Thanks @towardthesea!

**Pull request merged**
