### PR TITLE
Feature/iol reachable areas

### PR DESCRIPTION
**Pull request by Tobias-Fischer**

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Needs to be tested on the robot.

**Comment by Tobias-Fischer** [comment]
@pattacini can you please review?

**Comment by pattacini** [comment]
Sure @Tobias-Fischer
I'll need some time today; get you back late in the afternoon.
Stay tuned.

**Comment by Tobias-Fischer** [comment]
@gregoire-pointeau Please check https://github.com/robotology/wysiwyd/pull/151/commits/cd9c6a2cbfc682a9e56b4d126f74cf467bf3f8f4

**Comment by Tobias-Fischer** [comment]
@robotology/wysiwyd-developers In case this is being merged, you'll have to update the `object` table of your ABM and add a new column `objectarea` of type `text`.

**Comment by pattacini** [comment]
@Tobias-Fischer, this PR looks good to me :shipit:

**Comment by Tobias-Fischer** [comment]
Thanks for checking @pattacini! I'll merge as soon as it's been tested on the robot ..

**Comment by Tobias-Fischer** [comment]
Working nicely on the robot, thus merging.

**Pull request merged**
