### PR TITLE
Tracking objects with occlusions

### PR DESCRIPTION
**Pull request by pattacini**
Hey @robotology/wysiwyd-developers 

I'm happy to announce that we can now track objects with the `IOL` system even in presence of occlusions.

Here's an example: just double click on the snapshot below and you'll watch a quick video on this latest advancement.

[screeshot](https://ugo-pattacini.tinytake.com/sf/NDU2NjQ3XzI0NjAwMTI)

#### How to build the project

To enable the new feature you have to go through the following steps.

##### Build OpenCV-3.0.0

We need the new tracking features delivered with `OpenCV-3.0.0`:

1. Download `OpenCV-3.0.0`: `git clone https://github.com/Itseez/opencv.git`.
2. Checkout the correct branch: `git checkout 3.0.0`.
3. Download the external modules: `git clone https://github.com/Itseez/opencv_contrib.git`.
4. Checkout the correct branch: `git checkout 3.0.0`.
5. Configure `OpenCV` by filling in the cmake var **`OPENCV_EXTRA_MODULES_PATH`** with the path pointing to `opencv_contrib/modules` and then toggling on the var **`BUILD_opencv_tracking`**.
6. Compile `OpenCV`.

##### Build WYSIWYD

Configure the project:

1. Fill in the cmake var **`OpenCV_DIR`** with the path to `OpenCV-3.0.0` build.
2. Toggle on the cmake option **`WYSIWYD_IOL2OPC_WITH_TRACKING`**. Note that if this options is `OFF`, then we do not need `OpenCV-3.0.0` and the project still compiles with the previous versions.
3. Compile `wysiwyd`.

##### Building notes

It might be the case that you have also to build [**`kinect-wrapper`**](https://github.com/robotology/kinect-wrapper) with the new `OpenCV` library, as it was for me too. In particular, the setting I used foresees `yarp`, `icub-main` and all the other projects built with `OpenCV-2.x.y`, whereas `wysiwyd` along with `kinect-wrapper` built with `OpenCV-3.0.0`. This means that you can be perfectly working with two versions of the library available side by side. To ease compilation, I have also enabled the possibility to build only the client part of the `kinect-wrapper` (see [**updated instructions**](https://github.com/robotology/kinect-wrapper#cmaking-the-project)).

Finally, I would recommend to test the branch, experiment with this new tracking capability and, only afterwards, merge it.

#### How to use tracking

From an high-level perspective, the behavior is very simple: once the segmentation pipeline stops providing blobs due to big occlusions in the scene, then a tracker takes over it and keeps updating the object localization for a **tune-able time window**. 

To regulate the temporal width of such a window, play with the **`tracker_timeout`** parameter of the `iol2opc` module, which is by default set to `5.0 s`.

#### Concluding remarks

@gregoire-pointeau 
The `verbRec` module was quite messy (really badly messy :smirk:) in handling the yarp communication, therefore I committed some changes in this respect which might have possibly broken how the communication was intended with downstream modules (e.g. `humanRobotDumper`).

In particular, I fixed the rpc communication done in the `RFModule::respond()` method.

### CODE REVIEW

**Comment by matejhof** [comment]
Cool!
This make come handy in the reaching in clutter scenario too!

**Comment by gregoire-pointeau** [comment]
Hi Ugo, very impressive.
I have one quick question, around 10", the octopus disappears in the bottom left window for a few seconds, but is kept in the GUI. I guess it means it is still in the OPC also. Do you put some kind of filter?

**Comment by maxime-petit** [comment]
Nice one, Thanks Ugo!

./Max

**Comment by pattacini** [comment]
@gregoire-pointeau it should be the usual timeout of `1 s` (aka **`heartBeat`**) which manages the objects disappearing.

**Comment by Tobias-Fischer** [comment]
Hi @pattacini, @adamian, @dcam0050, @uriel-martinez,
before merging this PR I'd like to resolve some issues of OpenCV3 with SAM. I fixed most of the problems in https://github.com/robotology/wysiwyd/commit/e432b06f6646add477ee357405a67707cf774e94 however there are 5 errors still remaining.
@pattacini: You can look at the errors when enabling `WYSIWYD_USE_GPU`

The errors are:
```
/home/tobias/robot/wysiwyd/main/src/modules/samRelated/SAM/SAM_Drivers/visionDriver/src/visionDriver.cpp:137: error: no matching function for call to 'cv::cuda::CascadeClassifier::detectMultiScale(cv::cuda::GpuMat&, cv::cuda::GpuMat&, double, int, cv::Size)'
/home/tobias/robot/wysiwyd/main/src/modules/samRelated/SAM/SAM_Drivers/visionDriver/src/visionUtils.cpp:527: error: 'morphologyEx' is not a member of 'cv::cuda'
/home/tobias/robot/wysiwyd/main/src/modules/samRelated/SAM/SAM_Drivers/visionDriver/src/visionUtils.cpp:528: error: 'GaussianBlur' is not a member of 'cv::cuda'
/home/tobias/robot/wysiwyd/main/src/modules/samRelated/SAM/SAM_Drivers/visionDriver/src/visionUtils.cpp:597: error: 'Canny' is not a member of 'cv::cuda'
/home/tobias/robot/wysiwyd/main/src/modules/samRelated/SAM/SAM_Drivers/visionDriver/src/visionUtils.cpp:831: error: no match for 'operator*' (operand type is 'cv::MatCommaInitializer_<float>')
```
For `detectMultiScale`, the way it's called has changed
For `Canny`, this link should be interesting: http://docs.opencv.org/master/d0/d05/group__cudaimgproc.html#gsc.tab=0
For `GaussianBlur` and `morphologyEx`, see https://stackoverflow.com/questions/26909194/where-are-the-gpu-functions-on-opencv-3-0
I have no idea about the last error.

Would be great if one of you has a look and implement the changes, so we can sort it out.

Best,
Tobi

**Comment by pattacini** [comment]
Good catch @Tobias-Fischer 

To any rate, since I spent a couple of days already in porting the present code to the use of `opencv-3.x.y`, I deem it's up to you, guys in Sheffield, this time :smirk: 
And it's also your specific code, thus you know it better than everyone else.

**Comment by Tobias-Fischer** [comment]
Sounds reasonable. Would be great if you could fix this soon-ish @adamian @uriel-martinez @dcam0050 so we can merge this and all enjoy the new tracking features :).

**Comment by pattacini** [comment]
Just to be clear, apply the required changes within this branch (`feature/iol2opc-with-tracking`) and not on `master`.

**Comment by adamian** [comment]
Thanks for the catch and pointers guys! I don't touch the cpp code, hopefully @dcam0050 and @uriel-martinez can fix this soon.

**Comment by Tobias-Fischer** [comment]
I quickly changed SAM according to OpenCV3 so we can merge this ASAP in https://github.com/robotology/wysiwyd/commit/fef45ca9257d8c9432348018e88d8e6217b9ea30. 
@pattacini: We'll run some tests with the tracking tomorrow and merge afterwards if is runs as smoothly.
@dcam0050 @uriel-martinez: I didn't try running SAM with OpenCV3 and GPU, please do so and check whether it behaves as expected.

**Comment by Tobias-Fischer** [comment]
Hi @pattacini,

could you please update the config files in https://github.com/robotology/wysiwyd/tree/master/main/app/systemVisual/iol2opc/scripts to include the tracking?

**Comment by pattacini** [comment]
Wilco :smirk:

**Comment by Tobias-Fischer** [comment]
Hi @pattacini,
I'm happy to merge as soon as 
1. XML files are updated, and 
2. the patch regarding the occasional exception is committed as well :)

Thanks a lot, it works really nicely here in London as well! I think it's a great addition to the project, and will be helpful in the future.

Best, Tobi

**Comment by pattacini** [comment]
@Tobias-Fischer (1) and (2) just committed.

**Comment by Tobias-Fischer** [comment]
Just tested the new version, and it's working fine here.

Will merge after lunch if there are no objections from anyone by then.

Best, Tobi

**Comment by gregoire-pointeau** [comment]
Hi, if I follow your instruction @pattacini , I have the following errors while compiling `opencv`:

>Linking CXX shared library ../../lib/libopencv_imgcodecs.so
[ 11%] Built target opencv_imgcodecs
[ 11%] Built target opencv_videoio_pch_dephelp
[ 11%] Built target pch_Generate_opencv_videoio
[ 11%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_ffmpeg.cpp.o
In file included from /usr/local/src/robot/opencv/modules/videoio/src/cap_ffmpeg.cpp:45:0:
/usr/local/src/robot/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:1546:71: error: use of enum ‘AVCodecID’ without previous declaration
/usr/local/src/robot/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:1556:83: error: use of enum ‘AVCodecID’ without previous declaration
make[2]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_ffmpeg.cpp.o] Error 1
make[1]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
make: *** [all] Error 2

I have the good `3.0.0` of both `opencv` and `opencv_contrib`.

**Comment by Tobias-Fischer** [comment]
Google is your friend :). Set `WITH_FFMPEG` to false.

**Pull request merged**
