### PR TITLE
C++11 for statement used in iol2opc

### PR DESCRIPTION
**Pull request by pattacini**
To endorse @Tobias-Fischer's [comment](https://github.com/robotology/wysiwyd/commit/7b1af01fd62ec16b3023d3d7e2f978a8cd182d76#commitcomment-17133890) :wink:.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/wysiwyd/pull/116%23issuecomment-211052789%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/wysiwyd/pull/116%23issuecomment-211052789%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3A%29%5Cr%5CnI%27ll%20merge%20this%20after%20the%20review%2C%20just%20in%20case%20something%20goes%20wrong.%20Did%20you%20also%20see%20the%20new%20%60enum%60%20type%20which%20isn%27t%20implicitly%20casted%20into%20an%20integer%3F%20And%20I%20love%20the%20smart%20pointers%20..%22%2C%20%22created_at%22%3A%20%222016-04-17T16%3A31%3A51Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/wysiwyd/pull/116#issuecomment-211052789'>General Comment</a></b>
- <a href='https://github.com/Tobias-Fischer'></a> :)
I'll merge this after the review, just in case something goes wrong. Did you also see the new `enum` type which isn't implicitly casted into an integer? And I love the smart pointers ..

<a href='https://www.codereviewhub.com/robotology/wysiwyd/pull/116?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/wysiwyd/pull/116?approve=1'></a>&nbsp;<a href='https://github.com/robotology/wysiwyd/pull/116'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by pattacini** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/wysiwyd/pull/116'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by Tobias-Fischer** [comment]
:)
I'll merge this after the review, just in case something goes wrong. Did you also see the new `enum` type which isn't implicitly casted into an integer? And I love the smart pointers ..

**Comment by Tobias-Fischer** [comment]
Thanks @pattacini!

**Comment by pattacini** [comment]
:+1:

**Comment by pattacini** [comment]
:shipit:

**Pull request merged**
