### PR TITLE
recognitionOrder behaviour

### PR DESCRIPTION
**Pull request by dcam0050**
Addition of a behaviour (recognitionOrder) that interfaces with samSupervisor for the classification of actions.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/wysiwyd/pull/108%23issuecomment-206473460%22%2C%20%22https%3A//github.com/robotology/wysiwyd/pull/108%23issuecomment-206482275%22%2C%20%22https%3A//github.com/robotology/wysiwyd/pull/108%23issuecomment-208506963%22%2C%20%22https%3A//github.com/robotology/wysiwyd/pull/108%23issuecomment-208510424%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/wysiwyd/pull/108%23issuecomment-206473460%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Did%20you%20manage%20to%20test%20it%3F%22%2C%20%22created_at%22%3A%20%222016-04-06T17%3A21%3A33Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3121184%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jypuigbo%22%7D%7D%2C%20%7B%22body%22%3A%20%22Please%20change%20tabs%20to%20spaces.%22%2C%20%22created_at%22%3A%20%222016-04-06T17%3A38%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22Hi%2C%20there%20are%20still%20some%20tabs%20in%20%20%60main/CMakeLists.txt%60%20%20and%20%20%60main/app/reactiveLayer/behaviorManager/conf/default.ini%60.%20Furthermore%2C%20we%20cannot%20merge%20due%20to%20conflicts%3B%20please%20have%20a%20look%20what%20the%20conflicts%20are.%20Happy%20to%20merge%20otherwise%20%3A%29%22%2C%20%22created_at%22%3A%20%222016-04-11T19%3A11%3A25Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20should%20have%20changed%20the%20tabs%20to%20spaces%20in%20all%20files%20now%20and%20I%20did%20a%20local%5Cnmerge%20of%20the%20year-2-dem%20branch%20with%20the%20year-2-demo-SAM%20branch.%20That%20should%5Cnsolve%20the%20conflicts.%20Let%20me%20check.%5Cn%5CnOn%2011%20April%202016%20at%2020%3A11%2C%20Tobias%20Fischer%20%3Cnotifications%40github.com%3E%20wrote%3A%5Cn%5Cn%3E%20Hi%2C%20there%20are%20still%20some%20tabs%20in%20main/CMakeLists.txt%20and%5Cn%3E%20main/app/reactiveLayer/behaviorManager/conf/default.ini.%20Furthermore%2C%20we%5Cn%3E%20cannot%20merge%20due%20to%20conflicts%3B%20please%20have%20a%20look%20what%20the%20conflicts%20are.%5Cn%3E%20Happy%20to%20merge%20otherwise%20%3A%29%5Cn%3E%5Cn%3E%20%5Cu2014%5Cn%3E%20You%20are%20receiving%20this%20because%20you%20authored%20the%20thread.%5Cn%3E%20Reply%20to%20this%20email%20directly%20or%20view%20it%20on%20GitHub%5Cn%3E%20%3Chttps%3A//github.com/robotology/wysiwyd/pull/108%23issuecomment-208506963%3E%5Cn%3E%5Cn%22%2C%20%22created_at%22%3A%20%222016-04-11T19%3A19%3A46Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4288535%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dcam0050%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/wysiwyd/pull/108#issuecomment-206473460'>General Comment</a></b>
- <a href='https://github.com/jypuigbo'></a> Did you manage to test it?
- <a href='https://github.com/Tobias-Fischer'></a> Please change tabs to spaces.
- <a href='https://github.com/Tobias-Fischer'></a> Hi, there are still some tabs in  `main/CMakeLists.txt`  and  `main/app/reactiveLayer/behaviorManager/conf/default.ini`. Furthermore, we cannot merge due to conflicts; please have a look what the conflicts are. Happy to merge otherwise :)
- <a href='https://github.com/dcam0050'></a> I should have changed the tabs to spaces in all files now and I did a local
merge of the year-2-dem branch with the year-2-demo-SAM branch. That should
solve the conflicts. Let me check.
On 11 April 2016 at 20:11, Tobias Fischer <notifications@github.com> wrote:
> Hi, there are still some tabs in main/CMakeLists.txt and
> main/app/reactiveLayer/behaviorManager/conf/default.ini. Furthermore, we
> cannot merge due to conflicts; please have a look what the conflicts are.
> Happy to merge otherwise :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/robotology/wysiwyd/pull/108#issuecomment-208506963>
>

<a href='https://www.codereviewhub.com/robotology/wysiwyd/pull/108?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/wysiwyd/pull/108?approve=1'></a>&nbsp;<a href='https://github.com/robotology/wysiwyd/pull/108'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by jypuigbo** [comment]
Did you manage to test it?

**Comment by Tobias-Fischer** [comment]
Please change tabs to spaces.

**Comment by Tobias-Fischer** [comment]
Hi, there are still some tabs in  `main/CMakeLists.txt`  and  `main/app/reactiveLayer/behaviorManager/conf/default.ini`. Furthermore, we cannot merge due to conflicts; please have a look what the conflicts are. Happy to merge otherwise :)

**Comment by dcam0050** [comment]
I should have changed the tabs to spaces in all files now and I did a local
merge of the year-2-dem branch with the year-2-demo-SAM branch. That should
solve the conflicts. Let me check.

**Comment by pattacini** [comment]
:shipit:

**Pull request merged**
