### PR TITLE
Proactive tagging refactoring

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
This somehow makes the code in proactive tagging easier to understand for future developments.

@maxime-petit: can we please try whether still everything works?
@pattacini: can you please have a look over it whether it makes all sense?

Best, Tobi

### CODE REVIEW

**Comment by clement-moulin-frier** [comment]
Hi @Tobias-Fischer ,

Are you planning to merge this PR soon? I am asking because it will probably conflict with what I'm doing for #38 (`upf/renaming` branch, that I've further updated locally on my computer). 
It's maybe better I wait for this PR to be merged, then integrate my changes. (I actually already have some conflict between my branch and 2c26d97f8cef7e245dab93379d43f26fd9dd0aef, that I will solve as well).

Best,
Clément

**Comment by Tobias-Fischer** [comment]
Hi, yes I'll merge soon. Probably tomorrow before lunchtime if that's okay. Sorry for the inconvenience!

Best, Tobi

**Comment by clement-moulin-frier** [comment]
No problem, it was just to know. It is a good thing to have refactored this module a bit :)

**Comment by maxime-petit** [comment]
Working fine here in London, merged.

**Pull request merged**
