### PR TITLE
Handle more actions

### PR DESCRIPTION
**Pull request by jypuigbo**
Ready to be tested. Push and look_at are added, in order to allow for more orders by the human.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Hi @jypuigbo @sockchinglow,
This PR by now cannot be merged as it has conflicts. Can you please open a new PR with a single commit containing all the changes you want to make? You can see the files which actually changed here: https://github.com/robotology/wysiwyd/pull/84/files

Best, Tobi

**Comment by Tobias-Fischer** [comment]
Fixed with https://github.com/robotology/wysiwyd/commit/18c9bde7b784e39f5a6ee3012164b833ffe5c911 and https://github.com/robotology/wysiwyd/commit/4c11dc9c5c4949380de26255bed1c8184e8e6649

@jypuigbo Please uncomment the `push` functionality.

**Comment by Tobias-Fischer** [comment]
@jypuigbo As written before, can you please enable the `push` functionality? Or is there any reason why not to use it?

**Comment by jypuigbo** [comment]
It's just not been tested yet. Tomorrow we'll make sure it works safely.

As well as general cleaning of the code.

2016-03-27 13:32 GMT+02:00 Tobias Fischer <notifications@github.com>:

**Pull request closed without merging**
