### PR TITLE
fix for #16

### LINKED ISSUE #16: [iol2opc] Several issues in the communication with the OPC
Hi,
there is an issue with iol2opc. Thus far, adding objects in the OPC works nicely. However, if an object gets out of the scene, `m_present` is still set to `true`. We therefore need to find a way to
a) detect once an object is removed from the scene
b) find this object in the OPC and set `m_present=false`

The issue is that we don't keep track which objects are added to the OPC. I think we need to create a list with known objects, and keep this list up to date. What do you think, @pattacini?

Best,
Tobias

### PR DESCRIPTION
**Pull request by pattacini**
This should do pretty much what is required to fix #16.
@Tobias-Fischer, give it a try if you'll be willing to.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Hi Ugo,
Great, Thanks very much for this! Unfortunately, it does not work out of the box. To me, it seems that the `report` method of `ClassifierReporter` never gets called. It expects a `PortInfo` - unfortunately I haven't dealt with this yet and I have no idea how to fix it ...

Thanks again,
Tobias

**Comment by Tobias-Fischer** [comment]
The missing piece for that is:
`classifierReporter.setBridge(this);`
Then, at least the main loop starts, but still no images are drawn.

**Comment by pattacini** [comment]
Yep, as before I've just committed a sort of sketch but did not test it since I'll be away till next week.

To any rate, the idea is simple: upon first connection, the loading of names from the classifier is served in the `updateModule()`. This is the [code](https://github.com/robotology/wysiwyd/pull/17/files#diff-b8801a9bec63daae22b6862699f536cdR781) in charge of retrieving such info from `himrepClassifier`. It might be that this exchange is not successful and the state machine never switches to `Bridge::localization`.

Btw, did you update `himrepClassifier`? There's been a change for that.

**Comment by pattacini** [comment]
One more thing causing problems might be the handling of `heart-beats` of the available objects. You can find it [here](https://github.com/robotology/wysiwyd/pull/17/files#diff-775f19ea4992df65c659de4e8a8a988cR52): it's quite simple, but the way those methods are called in the code could lead to unexpected behaviors.

**Comment by Tobias-Fischer** [comment]
Hi Ugo,
I think everything works fine now, except of one small issue:
`remove_object(name)` removes the object from the classifier database, however `m_present` is still `1`. When called a second time, `m_present` is set to `0`. I expect this is some kind of issue with `commit` of OPCClient? I am off for the weekend, and will have a look next week.

PS: m_present checked via `yarp rpc /OPC/rpc` and `get (id x)`

Thanks again,
Tobias

**Comment by pattacini** [comment]
... or maybe the `remove_object(name)` body is not protected with mutex against the `updateOPC()`; the same should apply to the whole set of services.

**Comment by Tobias-Fischer** [comment]
Hi Ugo,
I fixed this bug, and would be happy to merge the pull request if you are. The issue is that `opcBlobs` and `opcScores` still contain the object in the first place, as this is retrieved from the classifier. As we also contain a list of objects in `db`, I check against this list to verify that the object is still present in the OPC (i.e. not removed). This works nicely.

Best, Tobias

**Comment by Tobias-Fischer** [comment]
I forgot to mention that https://github.com/robotology/himrep/commit/be684ab1d8ddb154dcec6e93745a1225fb372de0 breaks the whole pipeline if no objects are in the object recognition database, as then the reply is an empty bottle! Therefore, I suggest that linearClassifierModule returns `nack` or something in similar if the reply is empty, and we check against this value.

**Comment by pattacini** [comment]
Do you mean you're having a `seg-fault`?
Which module is crashing? `linearClassifierModule` or 'himrepClassifier'?

**Comment by Tobias-Fischer** [comment]
Hi,
the following happens:
1) Starting `iol2opc`, it tries to get the list of objects: `[INFO]Sending list request: [list]`
2) `himrepClassifier`: `command received: [list]`, then `Sending list request: objList`
3) `linearClassifierModule`: `command received: objList`; issue: sending empty bottle!
4) `himrepClassifier`: `yarp: BottleImpl reader failed, unrecognized object code 25`

And then everything gets stuck ..

Best, Tobias

**Comment by pattacini** [comment]
I was hoping not to touch `linearClassifierModule` and solve the problem otherwise; not possible then. I'll do the fix, stay tuned. Thanks @Tobias-Fischer.

**Comment by pattacini** [comment]
@Tobias-Fischer update `himrep` and `iol` repository, compile them and try again...

**Comment by Tobias-Fischer** [comment]
Now we have the `yarp: BottleImpl reader failed, unrecognized object code 25` problem in `iol2opc` ;-).

**Comment by Tobias-Fischer** [comment]
The previous issue simply happens the way the RPC ports are opened. I forgot to open first all modules but iol2opc, then connect, then open iol2opc and then connect the other ports. So all good and working perfectly!
Would be great if you add the `reply.addString` as above :+1: 

Thanks a lot, I am glad this module now seems to run nice and smooth.

Best, Tobias

**Comment by pattacini** [comment]
@Tobias-Fischer I've no access to the robot now and since I wanted to better understand this issue I coded this simple [snippet](https://files.zenhub.io/5549b6fbd40187b7722fa71c).

Compile the project and launch in a row `test_1`, `test_2`, `test_3` (a couple of connections will be automatically created); then do:
```
$> yarp rpc /iol2opc/rpc
>>go
>>empty
```

I don't see any problem in there. Can you have a look at it too?

**Comment by Tobias-Fischer** [comment]
Hi @pattacini,
finally everything works nicely! I ran into some more issues today in the morning, but now everything is resolved.
First, there was a check missing in himrepClassifier, which caused everything to get stuck. The diff to resolve this is here, could you please change iol accordingly?
```
diff --git a/src/himrepClassifier/classifier.cpp b/src/himrepClassifier/classifier.cpp
index 23c986c..6c85dcc 100644
--- a/src/himrepClassifier/classifier.cpp
+++ b/src/himrepClassifier/classifier.cpp
@@ -329,6 +329,10 @@ void Classifier::classify(Bottle *blobs, Bottle &reply)
     Bottle cmdClass,classReply;
     cmdClass.addString("recognize");
     rpcClassifier.write(cmdClass,classReply);
+    if(classReply.get(0).asString()=="nack") {
+        reply.addList();
+        return;
+    }
 
     // read image
     ImageOf<PixelRgb> *image=imgInput.read();
@@ -497,6 +501,7 @@ bool Classifier::respond(const Bottle& command, Bottle& reply)
         case CMD_LIST:
         {
             Bottle cmdList;
+            reply.addString("ack");
             cmdList.addString("objList");
             printf("Sending list request: %s\n",cmdList.toString().c_str());
             rpcClassifier.write(cmdList,reply);
```

Secondly, the issue with the empty object list was because iol2opc connected to himrepClassifier before himrepClassifier got the chance to connect to linearClassifier. Therefore, iol2opc asked for the list from himrepClassifier, which was at that time not connected to linearClassifier yet. Just a few moments after, the connection happened and all of the sudden the objects were present.
I changed the order of connections in the XML file accordingly, and will commit the changes in a second.

Hopefully everything runs smoothly now :+1: 

Thanks again and best wishes,
Tobias

**Comment by Tobias-Fischer** [comment]
Bugfix commited in: https://github.com/robotology/wysiwyd/commit/15db7c97f5d87cc5b88c20ffda7a569ba22701c9

**Comment by pattacini** [comment]
I've included your first fix to `himrepClassifier` (update `iol` repo), plus some other fixes regarding the handling of `"objList"` command.

The second fix (i.e. `reply.addString("ack");`) is not included yet because it does not seem correct to me: `linearModuleClassifier` already responds with an `"ack"` inside the reply which then gets passed on to `iol2opc`. To this end, did you recompile the `linearModuleClassifier`>

**Comment by Tobias-Fischer** [comment]
Hi,
unfortunately the "other fixes" break the classify / some other stuff, and objects are not recognized at all anymore. Could you please revert them?

Regarding the second fix: My bad, you are right. I did not setup the connection between linearModuleClassifier and himrepClassifier for my test, and that broke it. No need for that :).

Thanks,
Tobias

**Comment by pattacini** [comment]
Done, sorry for the glitch: I got confused by another command with the same tag `"objList"`: reverted.

**Comment by Tobias-Fischer** [comment]
Perfect, now everything works like a charm :+1: 

Thanks again! I am sure iol2opc will be very useful in the future. As soon as I have some free time, I will look at a better blob extraction mechanism.

Thanks, Tobias

**Comment by pattacini** [comment]
Btw, if we happen to talk about `iol` in the project, that's a nice showcase video recently shooted by @vtikha.

**Comment by Tobias-Fischer** [comment]
This is a nice video indeed! I wish the blob extraction worked as nicely over here .. we have to fiddle around quite a bit to get blobs detected.

**Comment by vtikha** [comment]
Hi @Tobias-Fischer , let's see if we can do something about that. Could you please post screenshots of: the output of the iCub's camera, the output of lumaChroma and the output of the blobExtractor?

**Comment by Tobias-Fischer** [comment]
Hi @vtikha,
I was actually able to fix the issues with the blob extraction by putting the table closer to the iCub. Also, I changed the camera parameters a little. Now it works quite nicely :). Thanks a lot for offering your help!

Unfortunately, after playing around with the system a little, I found that something is broken - again :(. I don't know what's going on, but I can only train one object. As soon as I add another object, only this object is returned by the `himrepClassifier`.

See this part of a log:
```
475105		19151.793075		INFO		Sending classification request: [clas] ((blob_0 (210.0 47.0 234.0 65.0)) (blob_1 (138.0 90.0 168.0 117.0)) (blob_2 (201.0 104.0 236.0 141.0)))
475112		19151.965376		INFO		Received reply: (blob_0 ((sp 0.836989))) (blob_1 ((sp 0.968588))) (blob_2 ((sp 0.804243)))
...
475123		19152.069642		INFO		Sending training request: [trai] ((abc (200.0 104.0 236.0 141.0)))
475126		19152.135466		INFO		Received reply: ack
...
475140		19152.458005		INFO		Sending classification request: [clas] ((blob_0 (210.0 47.0 234.0 65.0)) (blob_1 (138.0 90.0 168.0 116.0)) (blob_2 (200.0 104.0 236.0 141.0)) (blob_3 (252.0 155.0 320.0 201.0)))
475151		19152.684788		INFO		Received reply: (blob_0 ((abc 0.313083))) (blob_1 ((abc 0.08402))) (blob_2 ((abc 0.975771))) (blob_3 ((abc 0.486003)))
```

So all of the sudden the `sp` object seems to be not returned by the classifier anymore. Do you have any idea why that could be, Ugo @pattacini?

It is very weird .. 

Thanks,
Tobias

**Comment by pattacini** [comment]
Honestly I have no clue... it's too complicated to figure it out.
Tomorrow I might be able to book the robot and run a quick test. I'll let you know then.

In the meantime, look at this commit: https://github.com/robotology/wysiwyd/commit/7b2b338e8baef3c204f0bbb7f7b6484d5d5af661. It serves to avoid conflicts between **iol** and **wysiwyd** object databases.

**Comment by Tobias-Fischer** [comment]
Hi Ugo,

Maxime and I were able to find the error. For some reason, we must have changed some stuff in `himrepClassifier` and/or `linearClassifierModule` so a Bottle changed. Basically, the `objList` bottle looks as follows: `ack (obj1 obj2 obj3)`. In `himrepClassifier` we were looping over the size of this bottle, which is always 2. However, we actually want to iterate over the size of the list within the bottle.

We can fix the bug as follows:
```
diff --git a/src/himrepClassifier/classifier.cpp b/src/himrepClassifier/classifier.cpp
index ca57554..0dac5d3 100644
--- a/src/himrepClassifier/classifier.cpp
+++ b/src/himrepClassifier/classifier.cpp
@@ -407,7 +407,7 @@ void Classifier::classify(Bottle *blobs, Bottle &reply)
 
         // fill the list of the i-th blob
         printf("Scores received: ");
-        for (int i=0; i<objList.size()-1; i++)
+        for (int i=0; i<objList.get(1).asList()->size(); i++)
         {
             Bottle *obj=class_scores.get(i).asList();
             if (obj->get(0).asString()=="background")
```

Would you be so kind and change that?

Now hopefully (finally) everything should work nicely.

Thanks,
Tobias and Maxime

**Comment by pattacini** [comment]
Now that I can better realize what is going on you're asking me to apply exactly the fix causing the problem before, since everything narrows down to the modifications made to the `"objList"` command... uhm.

Sorry, I have to reapply my commit I reverted and tested tomorrow.

**Comment by pattacini** [comment]
This commit https://github.com/robotology/iol/commit/ab25abaef9648e8c0935f494581a301c4aa4f99d restores the previous one and adds some more fixes. Hopefully this will sort out the problem; we'll see tomorrow.

**Comment by pattacini** [comment]
Ok, tested: it's working here.
@Tobias-Fischer you could give it a try.

**Comment by Tobias-Fischer** [comment]
Working fine here as well :+1:.

Thanks a lot @pattacini 
Best, Tobias

**Comment by pattacini** [comment]
Great!

**Pull request merged**
