### PR TITLE
Feature/upf/push behaviors

### PR DESCRIPTION
**Pull request by towardthesea**
This PR to solve following problems:
- Introducing new safe waypoint after conducting action as mentioned in #163 
- Cleaning up the `subSystema_KARMA` to adapt with the new version of `karma`, named `karmaWYSIWYD` as mentioned in #170 

New features were fully tested!

@Tobias-Fischer could you please kindly have a look.

Cheers,
Phuong

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Hi @towardthesea,
Could you please open a separate PR with just the changes related to Karma?
Tip: I would create a new branch based on `devel`, and then `cherry-pick` the relevant commits from `feature/upf/pushBehaviors`.

See also below.

Best, Tobi

**Comment by Tobias-Fischer** [comment]
Hi @sockchinglow @jypuigbo @clement-moulin-frier,
I am against all these new behaviors. They are really, really hard to maintain, as 95% of the code is just copied across the files. If we see there is a small mistake in one file, all of the sudden we need to change it in 3 or 4 files.
I would suggest using OOP to circumvent this. Have one (abstract) class `pushingBehavior`, and then inherit `pushingFront`, `pushingLeft`, `pushingRight` from there. Then introduce variables which capture the 5% of the code which is not the same (i.e. `targetGroupName` which can be `targetFront` etc., `directionName` which can be `left` etc., and `function` which is a `std::function` variable).
Let me know if you have questions.

Best,
Tobi

**Comment by pattacini** [comment]
@towardthesea let's endorse the good suggestion from @Tobias-Fischer and make a proper PR.
We can make it up together.

**Comment by towardthesea** [comment]
@pattacini @Tobias-Fischer OK for me to make another PR!

**Comment by Tobias-Fischer** [comment]
Thanks @towardthesea @pattacini! Could you do the UPF guys a favor and rebase this branch on top of `devel` as soon as the other PR is merged? :)

**Comment by pattacini** [comment]
@Tobias-Fischer, job done

We've just created the `feature/iit/new-karma` branch and rebased `feature/upf/pushBehaviors` on top of `devel`.

@towardthesea is going to open a brand new PR right now.

**Comment by pattacini** [comment]
@sockchinglow please `git pull --rebase` your local copy of `feature/upf/pushBehaviors` and wait until the new PR will get merged to have the freshest karma things.

**Comment by pattacini** [comment]
See #174 for reviewing the new PR.

**Comment by sockchinglow** [comment]
@pattacini I have done a `pull --rebase` of my local branch, won't touch anything till the new PR for `karma`.

**Comment by pattacini** [comment]
@sockchinglow #174 has been merged, thus to get the new karma you'd need to `git rebase devel` your branch

**Pull request closed without merging**
