### PR TITLE
CVZ component removed from the repository

### PR DESCRIPTION
**Pull request by pattacini**
As per title and following up #144, this PR aims to remove outright the `CVZ` components from the repo, given this code is not used by the Consortium.

Developers in UPF, @clement-moulin-frier @jypuigbo @sockchinglow, might want to take a snapshot of `CVZ` and store it on a dedicated repository of theirs.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/wysiwyd/pull/146%23issuecomment-233030824%22%2C%20%22https%3A//github.com/robotology/wysiwyd/pull/146%23issuecomment-233328495%22%2C%20%22https%3A//github.com/robotology/wysiwyd/pull/146%23issuecomment-233330003%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/wysiwyd/pull/146%23issuecomment-233030824%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Looking%20good%2C%20thanks%20%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222016-07-15T18%3A28%3A46Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22We%20have%20backed%20it%20up%20here%20at%20UPF%2C%20we%20can%20merge.%5Cr%5CnThanks%22%2C%20%22created_at%22%3A%20%222016-07-18T13%3A30%3A20Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6000622%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/clement-moulin-frier%22%7D%7D%2C%20%7B%22body%22%3A%20%22Cool.%20I%20removed%20the%20references%20to%20GTK2%20from%20cmake%2C%20%40pattacini%20if%20you%27re%20happy%20with%20this%20please%20go%20ahead%20and%20merge%20%3A%29.%22%2C%20%22created_at%22%3A%20%222016-07-18T13%3A36%3A08Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/wysiwyd/pull/146#issuecomment-233030824'>General Comment</a></b>
- <a href='https://github.com/Tobias-Fischer'></a> Looking good, thanks :+1:
- <a href='https://github.com/clement-moulin-frier'></a> We have backed it up here at UPF, we can merge.
Thanks
- <a href='https://github.com/Tobias-Fischer'></a> Cool. I removed the references to GTK2 from cmake, @pattacini if you're happy with this please go ahead and merge :).

<a href='https://www.codereviewhub.com/robotology/wysiwyd/pull/146?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/wysiwyd/pull/146?approve=1'></a>&nbsp;<a href='https://github.com/robotology/wysiwyd/pull/146'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by pattacini** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/wysiwyd/pull/146'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by Tobias-Fischer** [comment]
Looking good, thanks :+1:

**Comment by clement-moulin-frier** [comment]
We have backed it up here at UPF, we can merge.
Thanks

**Comment by Tobias-Fischer** [comment]
Cool. I removed the references to GTK2 from cmake, @pattacini if you're happy with this please go ahead and merge :).

**Comment by pattacini** [comment]
:+1:

**Comment by pattacini** [comment]
:shipit:

**Pull request merged**
