### PR TITLE
New version of samSupervisor with rpc interface and README

### PR DESCRIPTION
**Pull request by dcam0050**
I will be uploading the models to a google drive and submitting the link soon
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/wysiwyd/pull/147%23issuecomment-236444887%22%2C%20%22https%3A//github.com/robotology/wysiwyd/pull/147%23issuecomment-236444984%22%2C%20%22https%3A//github.com/robotology/wysiwyd/pull/147%23issuecomment-236445049%22%2C%20%22https%3A//github.com/robotology/wysiwyd/pull/147%23issuecomment-236445326%22%2C%20%22https%3A//github.com/robotology/wysiwyd/pull/147%23issuecomment-236445398%22%2C%20%22https%3A//github.com/robotology/wysiwyd/pull/147%23issuecomment-236445683%22%2C%20%22https%3A//github.com/robotology/wysiwyd/pull/147%23issuecomment-236445864%22%2C%20%22https%3A//github.com/robotology/wysiwyd/pull/147%23issuecomment-236545765%22%2C%20%22https%3A//github.com/robotology/wysiwyd/pull/147%23issuecomment-237577543%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/wysiwyd/pull/147%23issuecomment-236444887%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Hi%20%40dcam0050%2C%5Cr%5Cn%5Cr%5CnThanks%20for%20the%20PR%21%20I%27m%20happy%20to%20see%20you%20got%20everything%20working%20as%20a%20proper%20module%20now.%5Cr%5CnI%27ve%20got%20some%20comments%20before%20merging%2C%20see%20them%20below%20in%20individual%20posts%20%3A%29.%5Cr%5Cn%5Cr%5CnBest%2C%20Tobi%22%2C%20%22created_at%22%3A%20%222016-07-31T17%3A43%3A07Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22Please%20delete%20the%20cmake%20build%20files%2C%20they%20shouldn%27t%20be%20in%20the%20repository%22%2C%20%22created_at%22%3A%20%222016-07-31T17%3A44%3A22Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22Please%20remove%20all%20unnecessary%20ipython%20notebooks%2C%20and%20leave%20only%20one%20of%20them%20in%20the%20repository%20%28clean%20all%20outputs%20of%20that%20one%29%22%2C%20%22created_at%22%3A%20%222016-07-31T17%3A45%3A09Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22%60motionMap%60%20is%20not%20a%20well%20designed%20yarp%20module.%20Rather%20than%20using%20a%20%60while%28true%29%60%2C%20use%20an%20RFModule%20and%20copy%20the%20contents%20within%20the%20%60while%60%20loop%20in%20the%20%60updateModule%60%20of%20the%20%60RFModule%60%20%28see%20basically%20any%20module%20within%20the%20repository%29.%20Also%2C%20please%20close%20the%20ports.%22%2C%20%22created_at%22%3A%20%222016-07-31T17%3A49%3A04Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22Not%20sure%20what%20this%20file%20is%3A%20%60main/src/modules/samRelated/SAM/Dev/plt%60%2C%20probably%20it%20shouldn%27t%20be%20in%20the%20repo.%22%2C%20%22created_at%22%3A%20%222016-07-31T17%3A50%3A08Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22Seems%20like%20%60%20main/src/modules/samRelated/SAM/SAM_Drivers/CMakeLists.txt%20%60%20is%20now%20useless%20and%20should%20be%20deleted.%22%2C%20%22created_at%22%3A%20%222016-07-31T17%3A53%3A54Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22Please%20create%20the%20PR%20such%20that%20you%20merge%20into%20%60devel%60%2C%20not%20%60master%60.%22%2C%20%22created_at%22%3A%20%222016-07-31T17%3A56%3A23Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22-%20%5B%5D%20Also%20please%20update%20the%20WYSIWYD%20year%202%20demo%20XML%20file%20in%20order%20to%20use%20the%20new%20module.%22%2C%20%22created_at%22%3A%20%222016-08-01T10%3A30%3A45Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%2C%20%7B%22body%22%3A%20%22-%20%5B%5D%20Also%20please%20clean%20the%20existing%20notebooks%2C%20such%20that%20no%20output%20is%20contained%3A%20https%3A//github.com/robotology/wysiwyd/search%3Fl%3Djupyter-notebook%22%2C%20%22created_at%22%3A%20%222016-08-04T14%3A52%3A10Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fischer%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/wysiwyd/pull/147#issuecomment-236444887'>General Comment</a></b>
- <a href='https://github.com/Tobias-Fischer'></a> Hi @dcam0050,
Thanks for the PR! I'm happy to see you got everything working as a proper module now.
I've got some comments before merging, see them below in individual posts :).
Best, Tobi
- <a href='https://github.com/Tobias-Fischer'></a> Please delete the cmake build files, they shouldn't be in the repository
- <a href='https://github.com/Tobias-Fischer'></a> Please remove all unnecessary ipython notebooks, and leave only one of them in the repository (clean all outputs of that one)
- <a href='https://github.com/Tobias-Fischer'></a> `motionMap` is not a well designed yarp module. Rather than using a `while(true)`, use an RFModule and copy the contents within the `while` loop in the `updateModule` of the `RFModule` (see basically any module within the repository). Also, please close the ports.
- <a href='https://github.com/Tobias-Fischer'></a> Not sure what this file is: `main/src/modules/samRelated/SAM/Dev/plt`, probably it shouldn't be in the repo.
- <a href='https://github.com/Tobias-Fischer'></a> Seems like ` main/src/modules/samRelated/SAM/SAM_Drivers/CMakeLists.txt ` is now useless and should be deleted.
- <a href='https://github.com/Tobias-Fischer'></a> Please create the PR such that you merge into `devel`, not `master`.
- <a href='https://github.com/Tobias-Fischer'></a> - [] Also please update the WYSIWYD year 2 demo XML file in order to use the new module.
- <a href='https://github.com/Tobias-Fischer'></a> - [] Also please clean the existing notebooks, such that no output is contained: https://github.com/robotology/wysiwyd/search?l=jupyter-notebook

<a href='https://www.codereviewhub.com/robotology/wysiwyd/pull/147?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/wysiwyd/pull/147?approve=1'></a>&nbsp;<a href='https://github.com/robotology/wysiwyd/pull/147'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by pattacini** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/wysiwyd/pull/147'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by Tobias-Fischer** [comment]
Hi @dcam0050,

Thanks for the PR! I'm happy to see you got everything working as a proper module now.
I've got some comments before merging, see them below in individual posts :).

Best, Tobi

**Comment by Tobias-Fischer** [comment]
Please delete the cmake build files, they shouldn't be in the repository

**Comment by Tobias-Fischer** [comment]
Please remove all unnecessary ipython notebooks, and leave only one of them in the repository (clean all outputs of that one)

**Comment by Tobias-Fischer** [comment]
`motionMap` is not a well designed yarp module. Rather than using a `while(true)`, use an RFModule and copy the contents within the `while` loop in the `updateModule` of the `RFModule` (see basically any module within the repository). Also, please close the ports.

**Comment by Tobias-Fischer** [comment]
Not sure what this file is: `main/src/modules/samRelated/SAM/Dev/plt`, probably it shouldn't be in the repo.

**Comment by Tobias-Fischer** [comment]
Seems like ` main/src/modules/samRelated/SAM/SAM_Drivers/CMakeLists.txt ` is now useless and should be deleted.

**Comment by Tobias-Fischer** [comment]
Please create the PR such that you merge into `devel`, not `master`.

**Comment by Tobias-Fischer** [comment]
- [] Also please update the WYSIWYD year 2 demo XML file in order to use the new module.

**Comment by Tobias-Fischer** [comment]
- [] Also please clean the existing notebooks, such that no output is contained: https://github.com/robotology/wysiwyd/search?l=jupyter-notebook

**Comment by Tobias-Fischer** [comment]
This is not rebased on top of `devel` .. please follow the instructions by @pattacini on Slack :)

**Pull request merged**
