### PR TITLE
Fix whitespace

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Replaces tabs with 4 spaces

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@gregoire-pointeau and @pattacini: Please check and merge :)

**Comment by Tobias-Fischer** [comment]
Please note that another solution would have been to use the auto-indent feature of your favorite code editor, however that would have affected far more files, and not everyone has the same preferences when it comes to indentation. Thus, here I just replaced tabs by 4 spaces, and no more.

**Comment by gregoire-pointeau** [comment]
Yep, I approve the fact to configure your text editor.
I just reinstalled it Tuesday and forgot to change it again...
But concerning the subsystem, I copied pasted the one from recog, which is with tabs.

**Comment by Tobias-Fischer** [comment]
This was not meant to be a comment to your recent commits ;). In this PR, I change all tabs to spaces, so there won't be any tabs in the repository anymore.

**Comment by pattacini** [comment]
For speeding up the review I've followed this [**suggestion**(]https://github.com/blog/967-github-secrets) in order not to consider white-spaces/tabs in the diff.

In the end it seems there are 9 files whose mode has been changed.

**Comment by pattacini** [comment]
Basically, click here to see this _smarter_ diff: https://github.com/robotology/wysiwyd/pull/64/files?w=1.

**Comment by Tobias-Fischer** [comment]
Yes, git automatically changed the mode of these files as `*.cpp` and `*.h` files should not be executable

**Comment by pattacini** [comment]
Cool, fine with me then. Merging ...
Thanks @Tobias-Fischer 

@robotology/wysiwyd-developers please be careful with tabs now :smirk:

**Pull request merged**
