### PR TITLE
Feature/sam related

### PR DESCRIPTION
**Pull request by dcam0050**
Request to merge updates with devel

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Happy to merge, as this only affects SAM related Python modules. Could you please send a link around with the models so this can be tested in other labs @dcam0050?
Thanks, Tobi

**Comment by dcam0050** [comment]
Here's the folder with the data and the pre trained models.

https://drive.google.com/open?id=0B6fkkRLTYjNLbjFFSEZtUmtHNk0

Download the root folder (SAM_Data_Models) as is and place in /home/icub (This is the current setting in default.ini otherwise you can place it anywhere and update this setting)

With the current settings in default.ini, the actions model should be loaded automatically when samSupervisor starts up. 

If windows are not required to monitor the process, set persistence and windowed settings in default.ini to False.

**Comment by Tobias-Fischer** [comment]
Thanks @dcam0050 
Can you please include the link in a Readme file or something? As soon as that's done, I'll merge if it's okay with you.

**Comment by dcam0050** [comment]
Included the link. Ready to merge :)

**Pull request merged**
