### PR TITLE
Update CONTRIBUTING.md with instructions for rebasing 

### PR DESCRIPTION
**Pull request by clement-moulin-frier**

### CODE REVIEW

**Comment by pattacini** [comment]
@clement-moulin-frier could you revise the instructions with the modifications I made to Slack?

**Comment by clement-moulin-frier** [comment]
OK, I do it now

**Comment by clement-moulin-frier** [comment]
Done :)

**Comment by pattacini** [comment]
Thanks @clement-moulin-frier

**Pull request merged**
